### ISSUE TITLE
Feature: Image replacement

### ISSUE THREAD

**Issue by rudnetto** [rudnetto/daciolo-chrome-extension#11]
The extension should change (almost) every image on page with Cabo Daciolo's pictures. Pretty similar with nCage extension.

What is needed:
- Implementation of image replacement
- Set of Cabo Daciolo's pictures

**Comment by LeeConnelly12** [comment]
@rudnetto I'll start working on this

**Comment by rudnetto** [comment]
PR #13 merged. Closing issue.
