### ISSUE TITLE
Add Babel and Webpack to project to enable ES6 usage

### ISSUE THREAD

**Issue by rudnetto** [rudnetto/daciolo-chrome-extension#14]
Add Node.js to the project (npm init), use **babel** to transpile our source files and use **webpack** to bundle vendor files and our source files.

Bundles:

- `app.bundle.js` transpile and bundle our source files (at the moment, content.js and rules.js)
- `vendor.bundle.js` bundle all third-party libraries used (at the moment, only jQuery lib)
All bundles should be generated to `build/` folder.
Update `manifest.json` to load bundle files instead of directly loading our source files

**Comment by Klowner** [comment]
I think I can get this done for you!

**Comment by rudnetto** [comment]
Okay @Klowner, looking forward to the pull request. I'm assigning this issue to you.

Thanks for contributing!
