### ISSUE TITLE
Trocar o nome Havan para Sede da Ursal

### ISSUE THREAD

**Issue by Koalapvh13** [rudnetto/daciolo-chrome-extension#17]
Trocar todas as ocorrências da palavra Havan por Sede da Ursal.

**Comment by rudnetto** [comment]
Olá @Koalapvh13! Obrigado pela contribuição! Acho que ficaria mais legal manter o que eu propus na issue #19, o que você acha? Vou fechar a issue e o PR. Podemos abrí-la novamente caso necessário.
