### ISSUE TITLE
Adicionar suporte para mais de uma regra de transformação de texto

### ISSUE THREAD

**Issue by rudnetto** [rudnetto/daciolo-chrome-extension#2]
A aplicação deverá ter um arquivo de regras de transformação `rules.js` que será lido em `content.js`.
Esse arquivo deve fornecer uma lista (array) de regras de transformação de texto.

Cada regra deverá fornecer:

Atributo | Tipo | Descrição
-------- | ----- | -----
selector | _string_ / _regex_ | String ou RegEx que será usado para selecionar texto
target | _string_ | Resultado da transformação. É possível utilizar `$&` para referenciar o texto selecionado.

As regras deverão ser processadas em ordem que forem declaradas em `rules.js`

**Comment by matheushf** [comment]
Mas quais regras você quer que tenha?

**Comment by rudnetto** [comment]
@matheushf pode fazer só a estrutura para suportar novas regras. Daí, adicionamos novas frases futuramente.

**Comment by rudnetto** [comment]
Se quiser mais uma regra pra adicionar na aplicação, faz uma regra que transforme as palavras `Brasil` ou `brasil` em `URSAL`

**Comment by matheushf** [comment]
Gloria a Deux, vê aí se tá bom #4

**Comment by rudnetto** [comment]
@matheushf adicionei algumas mudanças necessárias lá no pull request. Fazendo aquilo lá eu posso aprovar, valeu!

Não esquece de dar rebase com o remote pra não conflitar e etc.

**Comment by rudnetto** [comment]
Pull request #4 wans't enough and some errors are still being thrown. Gonna release another PR to correct this.
