### ISSUE TITLE
Add Babel and Webpack to project to enable ES6 usage

### ISSUE THREAD

**Issue by rudnetto** [rudnetto/daciolo-chrome-extension#5]
Add Node.js to the project (npm init), use **babel** to transpile our source files and use **webpack** to bundle vendor files and our source files.

Bundles:
- `app.bundle.js` transpile and bundle our source files (at the moment, `content.js` and `rules.js`)
- `vendor.bundle.js` bundle all third-party libraries used (at the moment, only jQuery lib)

All bundles should be generated to `build/` folder.
Update `manifest.json` to load bundle files instead of directly loading our source files

**Comment by joaaogui** [comment]
Fiz o PR #6

**Comment by rudnetto** [comment]
@joaaogui adicionei mais detalhes no PR que precisam ser feitos. Fazendo aquilo lá eu posso aceitar o PR. Valeu por contribuir!

**Comment by rudnetto** [comment]
@joaaogui alterei a descrição da issue, sentimos a necessidade de usar o webpack além do Babel, devido às limitações que temos no deploy das extensões

Portanto, vou fechar o PR #6 e peço que caso deseje continuar na issue, abra um novo PR.
